[package]
name = "adapters"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
reqwest = "0.12.23"
rust_decimal = "1.38.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.47.1"
