[package]
name = "oms"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
adapters = { path = "../adapters" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
log = "0.4"
thiserror = "1"
